const quotes = [
    "Life is about making an impact, not making an income. – Kevin Kruse",
    "Whatever the mind of man can conceive and believe, it can achieve. – Napoleon Hill",
    "Strive not to be a success, but rather to be of value. – Albert Einstein",
    "You miss 100% of the shots you don't take. – Wayne Gretzky",
    "I've missed more than 9000 shots in my career... And that is why I succeed. – Michael Jordan",
    "The most difficult thing is the decision to act, the rest is merely tenacity. – Amelia Earhart",
    "Every strike brings me closer to the next home run. – Babe Ruth",
    "Definiteness of purpose is the starting point of all achievement. – W. Clement Stone",
    "Life isn't about getting and having, it's about giving and being. – Kevin Kruse",
    "Life is what happens to you while you're busy making other plans. – John Lennon",
    "We become what we think about. – Earl Nightingale",
    "Twenty years from now you will be more disappointed by the things you didn’t do than by the ones you did do. – Mark Twain",
    "Life is 10% what happens to me and 90% of how I react to it. – Charles Swindoll",
    "The most common way people give up their power is by thinking they don't have any. – Alice Walker",
    "The mind is everything. What you think you become. – Buddha",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "An unexamined life is not worth living. – Socrates",
    "Eighty percent of success is showing up. – Woody Allen",
    "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
    "Winning isn’t everything, but wanting to win is. – Vince Lombardi",
    "I am not a product of my circumstances. I am a product of my decisions. – Stephen Covey",
    "Every child is an artist. The problem is how to remain an artist once he grows up. – Pablo Picasso",
    "You can never cross the ocean until you have the courage to lose sight of the shore. – Christopher Columbus",
    "People will never forget how you made them feel. – Maya Angelou",
    "Either you run the day, or the day runs you. – Jim Rohn",
    "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
    "The two most important days in your life are the day you are born and the day you find out why. – Mark Twain",
    "Whatever you can do, or dream you can, begin it. – Johann Wolfgang von Goethe",
    "The best revenge is massive success. – Frank Sinatra",
    "Motivation doesn’t last. Well, neither does bathing – that’s why we recommend it daily. – Zig Ziglar",
    "Life shrinks or expands in proportion to one’s courage. – Anaïs Nin",
    "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced. – Vincent Van Gogh",
    "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. – Aristotle",
    "Ask and it will be given to you; seek and you will find. – Jesus",
    "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
    "Go confidently in the direction of your dreams. – Henry David Thoreau",
    "Use everything you’ve been given. – Erma Bombeck",
    "Few things help more than responsibility and trust. – Booker T. Washington",
    "Certain things catch your eye, but pursue only those that capture the heart. – Indian Proverb",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "Everything you’ve ever wanted is on the other side of fear. – George Addair",
    "Men are afraid of the light. – Plato",
    "Admit ignorance and grow. – Maimonides",
    "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
    "Happiness was the key to life. – John Lennon",
    "Fall seven times and stand up eight. – Japanese Proverb",
    "Everything has beauty, not everyone sees it. – Confucius",
    "Start improving the world now. – Anne Frank",
    "Let go of what you are to become what you might be. – Lao Tzu",
    "Life is about breath-taking moments. – Maya Angelou",
    "Happiness comes from your own actions. – Dalai Lama",
    "If you’re offered a seat on a rocket ship, get on. – Sheryl Sandberg",
    "First, have a definite goal. – Aristotle",
    "If the wind will not serve, take to the oars. – Latin Proverb",
    "You can’t fall if you don’t climb. – Unknown",
    "You are gifted for something. – Marie Curie",
    "Don’t live your fears. – Les Brown",
    "Challenges make life meaningful. – Joshua J. Marine",
    "Lift someone else up. – Booker T. Washington",
    "Doing is urgent. – Leonardo da Vinci",
    "Limitations live only in our minds. – Jamie Paolinetti",
    "No one to blame but yourself. – Erica Jong",
    "Success is doing what you want daily. – Bob Dylan",
    "I found 100 ways to do it wrong. – Benjamin Franklin",
    "Desire success more than fear failure. – Bill Cosby",
    "No mistakes = no trying. – Albert Einstein",
    "Don’t interrupt the doers. – Chinese Proverb",
    "There are no traffic jams on the extra mile. – Roger Staubach",
    "It’s never too late to be what you might have been. – George Eliot",
    "You become what you believe. – Oprah Winfrey",
    "Die of passion, not boredom. – Vincent van Gogh",
    "Children are riches. – Unknown",
    "What we contribute gives life meaning. – Tony Robbins",
    "Courage reduces fear. – Rosa Parks",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Dream big and dare to fail. – Norman Vaughan",
    "Do one thing every day that scares you. – Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "Build your own dreams. – Farrah Gray",
    "Dreams don’t work unless you do. – John C. Maxwell",
    "Success is going from failure to failure without loss of enthusiasm. – Winston Churchill",
    "If you want something you never had, you must be willing to do something you’ve never done. – Thomas Jefferson",
    "Never give up on a dream just because of the time it will take to accomplish it. – Earl Nightingale",
    "Don’t wait. The time will never be just right. – Napoleon Hill",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "I hated every minute of training, but I said, ‘Don’t quit.’ – Muhammad Ali",
    "Push yourself, because no one else is going to do it for you. – Unknown",
    "Sometimes later becomes never. Do it now. – Unknown",
    "Great things never come from comfort zones. – Unknown",
    "Success doesn’t just find you. You have to go out and get it. – Unknown",
    "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown",
    "Dream bigger. Do bigger. – Unknown",
    "Don’t stop when you’re tired. Stop when you’re done. – Marilyn Monroe",
    "Wake up with determination. Go to bed with satisfaction. – George Lorimer",
    "Do something today that your future self will thank you for. – Sean Patrick Flanery"
  ];
  

const showQuotes= document.getElementById("quote");
const quoteButton= document.getElementById("generate")





quoteButton.addEventListener("click",()=>{
    const quoteId= Math.floor(Math.random()*quotes.length)
    console.log(quoteId)


    showQuotes.innerText=quotes[quoteId]
})


